export const ADD_CART_REQUEST = 'ADD_CART_REQUEST'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const UPDATE_CART_QUANTITY_REQUEST = 'UPDATE_CART_QUANTITY_REQUEST'
export const UPDATE_CART_QUANTITY_SUCCESS = 'UPDATE_CART_QUANTITY_SUCCESS'
export const UPDATE_CART_QUANTITY_FAIL = 'UPDATE_CART_QUANTITY_FAIL'


export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL'

export const DELETEALL_CART_REQUEST = 'DELETEALL_CART_REQUEST'
export const DELETEALL_CART_SUCCESS = 'DELETEALL_CART_SUCCESS'
export const DELETEALL_CART_FAIL = 'DELETEALL_CART_FAIL'