export const GET_COUPON_REQUEST = 'GET_COUPON_REQUEST'
export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS'
export const GET_COUPON_FAIL = 'GET_COUPON_FAIL'
export const REMOVE_COUPON = 'REMOVE_COUPON'