export const ADD_SUMMARY_REQUEST = 'ADD_SUMMARY_REQUEST'
export const ADD_SUMMARY_SUCCESS = 'ADD_SUMMARY_SUCCESS'
export const ADD_SUMMARY_FAIL = 'ADD_SUMMARY_FAIL'

export const GET_SUMMARY_REQUEST = 'GET_SUMMARY_REQUEST'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_FAIL = 'GET_SUMMARY_FAIL'