export const mainColor = '#ff8c00'
export const altColor = '#DCCA87'
export const labelColor = '#144e60'
export const mainPaddingTop = '100px'
export const mainPaddingBottom = '100px'
export const sectionBackground = '#292929'
export const mainTransition = '0.5s'